# A headless service which allows pods to discover the number of pods in the 
# stateful set by performing SRV queries.
apiVersion: v1
kind: Service
metadata:
  name: etherscan-headless
  namespace: etherscan
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 8080
    name: web
  selector:
    app: etherscan-monolith-instance
---
apiVersion: v1
kind: Service
metadata:
  name: etherscan-service
  namespace: etherscan
  labels:
    app: etherscan-monolith-instance
spec:
  ports:
  - name: prometheus
    port: 31933
    targetPort: 31933
    protocol: TCP
  selector:
    app: etherscan-monolith-instance
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etherscan-monolith-instance
  namespace: etherscan
  labels:
    app: etherscan-monolith-instance
spec:
  serviceName: etherscan-service
  selector:
    matchLabels:
      app: etherscan-monolith-instance
  replicas: 1
  template:
    metadata:
      labels:
        app: etherscan-monolith-instance
    spec:
      containers:
      - name: etherscan-monolith
        imagePullPolicy: Always
        image: localhost:5000/etherscan-monolith:latest
        args:
          - "-ethclient-local=false"
          - "-gravitas-num-workers=2"
          - "-gravitas-update-interval=1m"
          - "-partition-detection-mode=dns=etherscan-headless"
          - "-scanner-num-workers=10"
          - "-score-store-uri=postgresql://cdb-cockroachdb-public.etherscan-data:26257/etherscan?sslmode=disable"
          - "-tx-graph-uri=postgresql://cdb-cockroachdb-public.etherscan-data:26257/etherscan?sslmode=disable"
        ports:
        - name: prometheus
          containerPort: 31933
        - name: pprof
          containerPort: 6060
        resources:
          requests:
            cpu: "2"
