{
 "title": "etherscan",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "rate scanner blocks consumed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(etherscan_scanner_cnt[30s]))"
    }
   ]
  },
  {
   "title": "scanner blocks consumed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(etherscan_scanner_cnt)" }
   ]
  },
  {
   "title": "rate gravitas load wallets rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(etherscan_gravitas_load_wallets_cnt[30s]))"
    }
   ]
  },
  {
   "title": "gravitas wallets loaded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(etherscan_gravitas_load_wallets_cnt)"
    }
   ]
  }
 ]
}