apiVersion: v1
kind: Namespace
metadata:
  name: etherscan
  labels:
    role: etherscan-components
---
apiVersion: v1
kind: Namespace
metadata:
  name: etherscan-data
  labels:
    role: etherscan-data
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    role: monitoring
