# Setting overrides for the CDB helm chart at:
# https://github.com/helm/charts/tree/master/stable/cockroachdb
Resources:
  limits:
    cpu: "4"
    memory: "4G"
  requests:
    cpu: "1"
    memory: "1G"
Storage: "40G"
