// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/moratsam/etherscan/depl/monolith/service/gravitas (interfaces: GraphAPI,ScoreStoreAPI)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	scorestore "github.com/moratsam/etherscan/scorestore"
	graph "github.com/moratsam/etherscan/txgraph/graph"
)

// MockGraphAPI is a mock of GraphAPI interface.
type MockGraphAPI struct {
	ctrl     *gomock.Controller
	recorder *MockGraphAPIMockRecorder
}

// MockGraphAPIMockRecorder is the mock recorder for MockGraphAPI.
type MockGraphAPIMockRecorder struct {
	mock *MockGraphAPI
}

// NewMockGraphAPI creates a new mock instance.
func NewMockGraphAPI(ctrl *gomock.Controller) *MockGraphAPI {
	mock := &MockGraphAPI{ctrl: ctrl}
	mock.recorder = &MockGraphAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphAPI) EXPECT() *MockGraphAPIMockRecorder {
	return m.recorder
}

// WalletTxs mocks base method.
func (m *MockGraphAPI) WalletTxs(arg0 string) (graph.TxIterator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalletTxs", arg0)
	ret0, _ := ret[0].(graph.TxIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WalletTxs indicates an expected call of WalletTxs.
func (mr *MockGraphAPIMockRecorder) WalletTxs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalletTxs", reflect.TypeOf((*MockGraphAPI)(nil).WalletTxs), arg0)
}

// Wallets mocks base method.
func (m *MockGraphAPI) Wallets(arg0, arg1 string) (graph.WalletIterator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wallets", arg0, arg1)
	ret0, _ := ret[0].(graph.WalletIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Wallets indicates an expected call of Wallets.
func (mr *MockGraphAPIMockRecorder) Wallets(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wallets", reflect.TypeOf((*MockGraphAPI)(nil).Wallets), arg0, arg1)
}

// MockScoreStoreAPI is a mock of ScoreStoreAPI interface.
type MockScoreStoreAPI struct {
	ctrl     *gomock.Controller
	recorder *MockScoreStoreAPIMockRecorder
}

// MockScoreStoreAPIMockRecorder is the mock recorder for MockScoreStoreAPI.
type MockScoreStoreAPIMockRecorder struct {
	mock *MockScoreStoreAPI
}

// NewMockScoreStoreAPI creates a new mock instance.
func NewMockScoreStoreAPI(ctrl *gomock.Controller) *MockScoreStoreAPI {
	mock := &MockScoreStoreAPI{ctrl: ctrl}
	mock.recorder = &MockScoreStoreAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScoreStoreAPI) EXPECT() *MockScoreStoreAPIMockRecorder {
	return m.recorder
}

// UpsertScore mocks base method.
func (m *MockScoreStoreAPI) UpsertScore(arg0 *scorestore.Score) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertScore", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertScore indicates an expected call of UpsertScore.
func (mr *MockScoreStoreAPIMockRecorder) UpsertScore(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertScore", reflect.TypeOf((*MockScoreStoreAPI)(nil).UpsertScore), arg0)
}

// UpsertScorer mocks base method.
func (m *MockScoreStoreAPI) UpsertScorer(arg0 *scorestore.Scorer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertScorer", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertScorer indicates an expected call of UpsertScorer.
func (mr *MockScoreStoreAPIMockRecorder) UpsertScorer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertScorer", reflect.TypeOf((*MockScoreStoreAPI)(nil).UpsertScorer), arg0)
}
